# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Repository Dispatch
on:
  repository_dispatch:
    types: [run-test]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - name: API Testing 
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm run test:api
      - name: UI Testing
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}   
      - run: sudo apt-get update
      - run: sudo apt update
      - run: sudo apt install firefoxdriver
      - run: sudo apt install firefox
      - run: sudo apt-get --only-upgrade install google-chrome-stable
      - run: npx webdriver-manager update
      - run: npm run webdriver
      - run: npx webdriver-manager start --detach
      - run: npm run test:ui
      
