# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Repository Dispatch
on:
  repository_dispatch:
    types: [run-test]
  push:
    branches: [ main ]  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: npm ci
      - name: API Testing 
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm run test:api
      - name: Upload reports to AWS bucket
        run: aws s3 sync ./mochawesome-reports ${{ secrets.AWS_BUCKET }}/api-tests-report
        if: ${{ always() }}
      - name: UI Testing
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}   
      - run: sudo apt-get update
      - run: sudo apt update
      - run: sudo apt install firefoxdriver -y
      - run: sudo apt install firefox
      - run: sudo apt-get --only-upgrade install google-chrome-stable
      - run: npx webdriver-manager update
      - run: npm run webdriver
      - run: npx webdriver-manager start --detach
      - run: npm run test:ui
